{
 "title": "Osago Insurance Frontend",
 "tags": [ "nextjs" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{service=~\"osagoinsurance-frontend\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{service=~\"osagoinsurance-frontend\"}[$__range]))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "service:http_request_count:sum{service=\"osagoinsurance-frontend\"}"
    }
   ]
  },
  {
   "title": "Active requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(nodejs_active_requests_total{service=~\"osagoinsurance-frontend\"})"
    }
   ]
  },
  {
   "title": "Eventloop",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(nodejs_eventloop_lag_seconds{service=\"osagoinsurance-frontend\"}) by (service)"
    }
   ]
  },
  {
   "title": "Node.js version",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "sum(nodejs_version_info{service=~\"osagoinsurance-frontend\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\", container=~\"osagoinsurance-frontend\"}) by (service)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(http_request_codes{service=~\"osagoinsurance-frontend\", code=~\"4..\"}[5m])) by (service) / sum(increase(http_request_count{service=~\"osagoinsurance-frontend\"}[5m])) by (service)",
     "legendFormat": "4xx rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(http_request_codes{service=~\"osagoinsurance-frontend\", code=~\"5..\"}[5m])) by (service) / sum(increase(http_request_count{service=~\"osagoinsurance-frontend\"}[5m])) by (service)",
     "legendFormat": "5xx rate"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Apdex score" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(rate(http_request_duration_ms_bucket{service=\"osagoinsurance-frontend\", le=\"0.5\"}[1m])) by (service)\n+\n  sum(rate(http_request_duration_ms_bucket{service=\"osagoinsurance-frontend\", le=\"1\"}[1m])) by (service)\n) / 2 / sum(rate(http_request_duration_ms_count{service=\"osagoinsurance-frontend\"}[1m])) by (service)"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(http_request_duration_percentiles{service=\"osagoinsurance-frontend\", quantile=~\"0.99\"}) by (quantile, service)",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Response Time / Route",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(http_route_duration_ms{service=~\"osagoinsurance-frontend\"}) by (route)",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "service:http_request_count:sum{service=\"osagoinsurance-frontend\"}",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Throughput / Route",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_route_codes{service=~\"osagoinsurance-frontend\"}[5m])) by (route)",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_codes{service=~\"osagoinsurance-frontend\", code=~\"5..\"}[5m])) by (service)",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(rate(http_request_codes{service=~\"osagoinsurance-frontend\", code=~\"4..\"}[5m])) by (service)",
     "legendFormat": "4xx"
    }
   ]
  },
  {
   "title": "Errors / Route",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum by (route, code) (rate(http_route_codes{service=~\"osagoinsurance-frontend\", code=~\"5..\"}[5m]))",
     "legendFormat": "{{code}} {{route}}"
    },
    {
     "expr": "sum by (route, code) (rate(http_route_codes{service=~\"osagoinsurance-frontend\", code=~\"4..\"}[5m]))",
     "legendFormat": "{{code}} {{route}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(eagle_pod_container_resource_usage_memory_bytes{datacenter=~\"azure\",namespace=\"sravni\",container=~\"osagoinsurance-frontend\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "avg(eagle_pod_container_resource_requests_memory_bytes{datacenter=~\"azure\",namespace=\"sravni\",container=\"osagoinsurance-frontend\"})",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(rate(eagle_pod_container_resource_usage_cpu_cores{container=~\"osagoinsurance-frontend\",namespace=\"sravni\",datacenter=~\"azure\"}[5m])) * 100",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "avg (eagle_pod_container_resource_limits_cpu_cores{container=~\"osagoinsurance-frontend\",namespace=\"sravni\",datacenter=~\"azure\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg (eagle_pod_container_resource_requests_cpu_cores{container=~\"osagoinsurance-frontend\",namespace=\"sravni\",datacenter=~\"azure\"})",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "title": "Memory cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(nodejs_memory_cache_keys{service=\"osagoinsurance-frontend\"}) by (service)",
     "legendFormat": "cache keys"
    },
    {
     "expr": "avg(rate(nodejs_memory_cache_hit{service=\"osagoinsurance-frontend\"}[5m])) by (service)",
     "legendFormat": "cache hit"
    },
    {
     "expr": "avg(rate(nodejs_memory_cache_miss{service=\"osagoinsurance-frontend\"}[5m])) by (service)",
     "legendFormat": "cache miss"
    },
    {
     "expr": "avg(rate(nodejs_memory_cache_updates{service=\"osagoinsurance-frontend\"}[5m])) by (service)",
     "legendFormat": "cache updates"
    },
    {
     "expr": "avg(rate(nodejs_memory_cache_updates_errors{service=\"osagoinsurance-frontend\"}[5m])) by (service)",
     "legendFormat": "cache updates errors"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_network_receive_bytes_total{image!=\"\", name=~\"^k8s_.*\", pod=~\"osagoinsurance-frontend-.*\"}[1m])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "- sum (rate(container_network_transmit_bytes_total{image!=\"\", name=~\"^k8s_.*\", pod=~\"osagoinsurance-frontend-.*\"}[1m])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Error rate alert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_codes{service=~\"osagoinsurance-frontend\", code=~\"5..\"}[5m])) by (service) / sum(increase(http_request_count{service=~\"osagoinsurance-frontend\"}[5m])) by (service)",
     "legendFormat": "error rate"
    }
   ]
  },
  {
   "title": "Restarts alert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{service=~\"osagoinsurance-frontend\"}[5m]))",
     "legendFormat": "restarts"
    }
   ]
  }
 ]
}