/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v1/cookies": {
    /** Получение кук */
    post: {
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["Sravni.Cookies.Service.v1.Models.CookiesRequestModel"];
          "application/json": components["schemas"]["Sravni.Cookies.Service.v1.Models.CookiesRequestModel"];
          "text/json": components["schemas"]["Sravni.Cookies.Service.v1.Models.CookiesRequestModel"];
          "application/*+json": components["schemas"]["Sravni.Cookies.Service.v1.Models.CookiesRequestModel"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Sravni.Cookies.Service.v1.Models.CookiesResponseModel"];
            "application/json": components["schemas"]["Sravni.Cookies.Service.v1.Models.CookiesResponseModel"];
            "text/json": components["schemas"]["Sravni.Cookies.Service.v1.Models.CookiesResponseModel"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
        /** @description Server Error */
        500: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description Информация о куке */
    "Sravni.Cookies.Service.v1.Models.Cookie": {
      /** @description Имя куки */
      name?: string | null;
      /** @description Значение куки */
      value?: string | null;
      /** @description Домен */
      domain?: string | null;
      /** @description Путь */
      path?: string | null;
      /** @description HttpOnly */
      httpOnly?: boolean;
      /**
       * Format: date-time
       * @description Время устаревания куки
       */
      expires?: string | null;
      /** @description Secure-кука? */
      secure?: boolean;
      /** @description SameSite */
      sameSite?: string | null;
      /**
       * Format: int32
       * @description Максимальный возраст куки в секундах
       */
      maxAge?: number | null;
    };
    /** @description Модель запроса для получения кук */
    "Sravni.Cookies.Service.v1.Models.CookiesRequestModel": {
      /** @description Коллекция кук */
      cookies?: components["schemas"]["System.Collections.Generic.KeyValuePair`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]"][] | null;
      /** @description Url, по которому пришел пользователь */
      url?: string | null;
      /** @description Referer */
      referer?: string | null;
    };
    /** @description Модель ответа для получения кук */
    "Sravni.Cookies.Service.v1.Models.CookiesResponseModel": {
      redirect?: components["schemas"]["Sravni.Cookies.Service.v1.Models.Redirect"];
      /** @description Информация о куках */
      cookies?: components["schemas"]["Sravni.Cookies.Service.v1.Models.Cookie"][] | null;
    };
    /** @description Информация о редиректе */
    "Sravni.Cookies.Service.v1.Models.Redirect": {
      /** @description Адрес для редиректа */
      location?: string | null;
      /**
       * Format: int32
       * @description Код редиректа
       */
      code?: number;
    };
    "Sravni.Micro.Errors.Error": {
      code?: string | null;
      target?: string | null;
      message?: string | null;
      attemptedValue?: string | null;
      details?: components["schemas"]["Sravni.Micro.Errors.Error"][] | null;
    };
    "Sravni.Micro.Errors.ErrorModel": {
      error?: components["schemas"]["Sravni.Micro.Errors.Error"];
    };
    "System.Collections.Generic.KeyValuePair`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]": {
      key?: string | null;
      value?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
