/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v1/companies": {
    get: {
      parameters: {
        query?: {
          status?: components["schemas"]["Sravni.InsuranceCompanies.Shared.Status"];
          locationRoute?: string;
          ids?: number[];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Sravni.InsuranceCompanies.Shared.Company"][];
            "application/json": components["schemas"]["Sravni.InsuranceCompanies.Shared.Company"][];
            "text/json": components["schemas"]["Sravni.InsuranceCompanies.Shared.Company"][];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
        /** @description Server Error */
        500: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
      };
    };
  };
  "/v1/companies-full": {
    get: {
      parameters: {
        query?: {
          limit?: number;
          skip?: number;
          status?: components["schemas"]["Sravni.InsuranceCompanies.Shared.Status"];
          locationRoute?: string;
          ids?: number[];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Sravni.InsuranceCompanies.Shared.PagedData`1[[Sravni.InsuranceCompanies.Shared.CompanyExtended, Sravni.InsuranceCompanies.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
            "application/json": components["schemas"]["Sravni.InsuranceCompanies.Shared.PagedData`1[[Sravni.InsuranceCompanies.Shared.CompanyExtended, Sravni.InsuranceCompanies.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
            "text/json": components["schemas"]["Sravni.InsuranceCompanies.Shared.PagedData`1[[Sravni.InsuranceCompanies.Shared.CompanyExtended, Sravni.InsuranceCompanies.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
        /** @description Server Error */
        500: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
      };
    };
  };
  "/v1/companies/names": {
    get: {
      parameters: {
        query?: {
          term?: string;
          products?: components["schemas"]["Sravni.InsuranceCompanies.ProductEnum"][];
          limit?: number;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Sravni.InsuranceCompanies.Shared.SuggestedOrganization"][];
            "application/json": components["schemas"]["Sravni.InsuranceCompanies.Shared.SuggestedOrganization"][];
            "text/json": components["schemas"]["Sravni.InsuranceCompanies.Shared.SuggestedOrganization"][];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
        /** @description Server Error */
        500: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
      };
    };
  };
  "/v1/company-details/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Sravni.InsuranceCompanies.Shared.Company"];
            "application/json": components["schemas"]["Sravni.InsuranceCompanies.Shared.Company"];
            "text/json": components["schemas"]["Sravni.InsuranceCompanies.Shared.Company"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
        /** @description Server Error */
        500: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
      };
    };
  };
  "/v1/company-details/{id}/full": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Sravni.InsuranceCompanies.Shared.CompanyExtended"];
            "application/json": components["schemas"]["Sravni.InsuranceCompanies.Shared.CompanyExtended"];
            "text/json": components["schemas"]["Sravni.InsuranceCompanies.Shared.CompanyExtended"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
        /** @description Server Error */
        500: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
      };
    };
  };
  "/v1/company-details/{alias}": {
    get: {
      parameters: {
        path: {
          alias: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Sravni.InsuranceCompanies.Shared.Company"];
            "application/json": components["schemas"]["Sravni.InsuranceCompanies.Shared.Company"];
            "text/json": components["schemas"]["Sravni.InsuranceCompanies.Shared.Company"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
        /** @description Server Error */
        500: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
      };
    };
  };
  "/v1/companies/{id}/products": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Sravni.InsuranceCompanies.Shared.CompanyProducts"];
            "application/json": components["schemas"]["Sravni.InsuranceCompanies.Shared.CompanyProducts"];
            "text/json": components["schemas"]["Sravni.InsuranceCompanies.Shared.CompanyProducts"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
        /** @description Server Error */
        500: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
      };
    };
  };
  "/v1/widgetholders/{source}": {
    get: {
      parameters: {
        path: {
          source: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Sravni.InsuranceCompanies.Data.WH.WidgetHolder"];
            "application/json": components["schemas"]["Sravni.InsuranceCompanies.Data.WH.WidgetHolder"];
            "text/json": components["schemas"]["Sravni.InsuranceCompanies.Data.WH.WidgetHolder"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
        /** @description Server Error */
        500: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
      };
    };
  };
  "/v1/widgetholders-by-encryptId/{encryptId}": {
    get: {
      parameters: {
        path: {
          encryptId: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Sravni.InsuranceCompanies.Data.WH.WidgetHolder"];
            "application/json": components["schemas"]["Sravni.InsuranceCompanies.Data.WH.WidgetHolder"];
            "text/json": components["schemas"]["Sravni.InsuranceCompanies.Data.WH.WidgetHolder"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
        /** @description Server Error */
        500: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    "Sravni.InsuranceCompanies.Data.WH.WidgetHolder": {
      sources?: string[] | null;
      sendOsagoPayMail?: boolean;
      isOffline?: boolean;
      name?: string | null;
      /** Format: int32 */
      id?: number;
    };
    /** @enum {string} */
    "Sravni.InsuranceCompanies.ProductEnum": "osago" | "kasko" | "vzr" | "realEstate";
    "Sravni.InsuranceCompanies.Shared.Branding": {
      hexColorBack?: string | null;
      hexColorName?: string | null;
      nameFirstLetter?: string;
    };
    "Sravni.InsuranceCompanies.Shared.Company": {
      /** Format: int32 */
      id?: number;
      alias?: string | null;
      code?: string | null;
      name?: string | null;
      fullName?: string | null;
      inn?: string | null;
      raRating?: string | null;
      /** Format: double */
      raRatingNumeric?: number;
      raRatingDescription?: string | null;
      phones?: string[] | null;
      status?: components["schemas"]["Sravni.InsuranceCompanies.Shared.Status"];
      isRecomended?: boolean;
      /** Format: int32 */
      foundationYear?: number | null;
      /** Format: int32 */
      yearsWithSravni?: number | null;
    };
    "Sravni.InsuranceCompanies.Shared.CompanyExtended": {
      /** Format: int32 */
      id?: number;
      alias?: string | null;
      code?: string | null;
      name?: string | null;
      fullName?: string | null;
      inn?: string | null;
      raRating?: string | null;
      /** Format: double */
      raRatingNumeric?: number;
      raRatingDescription?: string | null;
      phones?: string[] | null;
      status?: components["schemas"]["Sravni.InsuranceCompanies.Shared.Status"];
      isRecomended?: boolean;
      /** Format: int32 */
      foundationYear?: number | null;
      /** Format: int32 */
      yearsWithSravni?: number | null;
      description?: string | null;
      address?: string | null;
      license?: string | null;
      /** Format: int32 */
      licenseNumber?: number;
      web?: components["schemas"]["Sravni.InsuranceCompanies.Shared.WebAddress"];
      branding?: components["schemas"]["Sravni.InsuranceCompanies.Shared.Branding"];
      mobileAppLinks?: components["schemas"]["Sravni.InsuranceCompanies.Shared.MobileAppsLinks"];
      personalAccount?: components["schemas"]["Sravni.InsuranceCompanies.Shared.PersonalAccount"];
      prediction?: string | null;
    };
    "Sravni.InsuranceCompanies.Shared.CompanyProducts": {
      /** Format: int32 */
      companyId?: number;
      hasKasko?: boolean;
      hasOsago?: boolean;
      hasVzr?: boolean;
      hasRealEstate?: boolean;
      hasDms?: boolean;
      hasAccident?: boolean;
      hasNszh?: boolean;
    };
    "Sravni.InsuranceCompanies.Shared.MobileAppsLinks": {
      iOsAppLink?: string | null;
      androidPlayMarketLink?: string | null;
      androidAppGaleryLink?: string | null;
      androidGetAppsLink?: string | null;
      androidSamsungGalaxyStoreLink?: string | null;
      androidRuMarketLink?: string | null;
      androidRuStoreLink?: string | null;
    };
    "Sravni.InsuranceCompanies.Shared.PagedData`1[[Sravni.InsuranceCompanies.Shared.CompanyExtended, Sravni.InsuranceCompanies.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]": {
      items?: components["schemas"]["Sravni.InsuranceCompanies.Shared.CompanyExtended"][] | null;
      /** Format: int32 */
      total?: number;
    };
    "Sravni.InsuranceCompanies.Shared.PersonalAccount": {
      personalAccountName?: string | null;
      personalAccountLink?: string | null;
    };
    /** @enum {string} */
    "Sravni.InsuranceCompanies.Shared.Status": "active" | "archived";
    "Sravni.InsuranceCompanies.Shared.SuggestedOrganization": {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      alias?: string | null;
    };
    "Sravni.InsuranceCompanies.Shared.WebAddress": {
      url?: string | null;
      title?: string | null;
    };
    "Sravni.Micro.Errors.Error": {
      code?: string | null;
      target?: string | null;
      message?: string | null;
      attemptedValue?: string | null;
      details?: components["schemas"]["Sravni.Micro.Errors.Error"][] | null;
    };
    "Sravni.Micro.Errors.ErrorModel": {
      error?: components["schemas"]["Sravni.Micro.Errors.Error"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
