/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v2/calculations/{calcHash}": {
    /** Результат расчета */
    get: {
      parameters: {
        path: {
          calcHash: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.PollingResult"];
            "application/json": components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.PollingResult"];
            "text/json": components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.PollingResult"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
        /** @description Server Error */
        500: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
      };
    };
  };
  "/v2/calculations/multi/{calcHash}": {
    /** Результат расчета с множественными одобренными заказами */
    get: {
      parameters: {
        path: {
          calcHash: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.ExtPollingResult"];
            "application/json": components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.ExtPollingResult"];
            "text/json": components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.ExtPollingResult"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
        /** @description Server Error */
        500: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
      };
    };
  };
  "/v2/calculations/comparePolicies/{calcHash}": {
    /** Сравнивает старый и новый полисы */
    get: {
      parameters: {
        path: {
          calcHash: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Sravni.OsagoGateway.Service.Calculations.Models.ComparePolicies.ComparePoliciesResult"];
            "application/json": components["schemas"]["Sravni.OsagoGateway.Service.Calculations.Models.ComparePolicies.ComparePoliciesResult"];
            "text/json": components["schemas"]["Sravni.OsagoGateway.Service.Calculations.Models.ComparePolicies.ComparePoliciesResult"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
        /** @description Server Error */
        500: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
      };
    };
  };
  "/v2/calculations/prolongationcalculations/{hash}": {
    /** Возвращает расчет с рекомендациями о пролонгации */
    get: {
      parameters: {
        path: {
          /** @description Идентификатор расчета, зашифрованный */
          hash: string;
        };
      };
      responses: {
        /** @description ок */
        200: {
          content: {
            "text/plain": components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Recommendations.PollingWithRecomendationResult"];
            "application/json": components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Recommendations.PollingWithRecomendationResult"];
            "text/json": components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Recommendations.PollingWithRecomendationResult"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
        /** @description Расчёт с hash не найден */
        404: {
          content: never;
        };
        /** @description ошибка сервера */
        500: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
      };
    };
  };
  "/v2/profile/people": {
    /** Запрос людей из профиля пользователя */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Sravni.OsagoGateway.Service.Core.UserRequest"];
          "text/json": components["schemas"]["Sravni.OsagoGateway.Service.Core.UserRequest"];
          "application/*+json": components["schemas"]["Sravni.OsagoGateway.Service.Core.UserRequest"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.ProfileLoader.Models.ProfilePeopleForm"];
            "application/json": components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.ProfileLoader.Models.ProfilePeopleForm"];
            "text/json": components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.ProfileLoader.Models.ProfilePeopleForm"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: never;
        };
        /** @description Forbidden */
        403: {
          content: never;
        };
        /** @description Server Error */
        500: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
      };
    };
  };
  "/v2/promo/link": {
    /** Привязывает полученный промокод к заказу при прохождении всех валидаций. */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Sravni.OsagoPromo.Shared.Models.LinkPromoCodeRequest"];
          "text/json": components["schemas"]["Sravni.OsagoPromo.Shared.Models.LinkPromoCodeRequest"];
          "application/*+json": components["schemas"]["Sravni.OsagoPromo.Shared.Models.LinkPromoCodeRequest"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": string;
            "application/json": string;
            "text/json": string;
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: never;
        };
        /** @description Forbidden */
        403: {
          content: never;
        };
        /** @description Server Error */
        500: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
      };
    };
  };
  "/v2/promo/check": {
    /** Проверяет введенный промокод */
    post: {
      parameters: {
        query?: {
          code?: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Sravni.OsagoPromo.Shared.Models.PromoCodeValidationResult"];
            "application/json": components["schemas"]["Sravni.OsagoPromo.Shared.Models.PromoCodeValidationResult"];
            "text/json": components["schemas"]["Sravni.OsagoPromo.Shared.Models.PromoCodeValidationResult"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: never;
        };
        /** @description Forbidden */
        403: {
          content: never;
        };
        /** @description Server Error */
        500: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
      };
    };
  };
  "/v2/promo/info": {
    /** Получает информацию о промокоде */
    post: {
      parameters: {
        query?: {
          code?: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Sravni.OsagoPromo.Shared.Models.PromoCodeInfo"];
            "application/json": components["schemas"]["Sravni.OsagoPromo.Shared.Models.PromoCodeInfo"];
            "text/json": components["schemas"]["Sravni.OsagoPromo.Shared.Models.PromoCodeInfo"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: never;
        };
        /** @description Forbidden */
        403: {
          content: never;
        };
        /** @description Server Error */
        500: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
      };
    };
  };
  "/v2/promo/show": {
    /** Получает информацию о промокоде */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Sravni.OsagoGateway.Service.Calculations.Models.StartCalculationRequest"];
          "text/json": components["schemas"]["Sravni.OsagoGateway.Service.Calculations.Models.StartCalculationRequest"];
          "application/*+json": components["schemas"]["Sravni.OsagoGateway.Service.Calculations.Models.StartCalculationRequest"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Sravni.Osago.ShowPromoDto"];
            "application/json": components["schemas"]["Sravni.Osago.ShowPromoDto"];
            "text/json": components["schemas"]["Sravni.Osago.ShowPromoDto"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: never;
        };
        /** @description Forbidden */
        403: {
          content: never;
        };
        /** @description Server Error */
        500: {
          content: {
            "text/plain": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "application/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
            "text/json": components["schemas"]["Sravni.Micro.Errors.ErrorModel"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    "Sravni.Micro.Errors.Error": {
      code?: string | null;
      target?: string | null;
      message?: string | null;
      attemptedValue?: string | null;
      details?: components["schemas"]["Sravni.Micro.Errors.Error"][] | null;
    };
    "Sravni.Micro.Errors.ErrorModel": {
      error?: components["schemas"]["Sravni.Micro.Errors.Error"];
    };
    "Sravni.Osago.ShowPromoDto": {
      canShow?: boolean;
    };
    /** @description Данные о документе на ТС */
    "Sravni.OsagoGateway.Service.Calculations.Models.CarDocumentInfoNullableDate": {
      /** @description Серия */
      series?: string | null;
      /** @description Номер */
      number?: string | null;
      /**
       * Format: date-time
       * @description Дата выдачи
       */
      date?: string | null;
      documentType?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.CarDocumentType"];
    };
    "Sravni.OsagoGateway.Service.Calculations.Models.ComparePolicies.BannerModel": {
      title?: string | null;
      description?: string | null;
      action?: string | null;
      companyList?: components["schemas"]["Sravni.OsagoGateway.Service.Calculations.Models.ComparePolicies.CompanyModel"][] | null;
      /** Format: int32 */
      previousCompanyId?: number;
    };
    "Sravni.OsagoGateway.Service.Calculations.Models.ComparePolicies.Column": {
      value?: string | null;
      descriptions?: string[] | null;
      color?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.ColorType"];
      popupText?: string | null;
      bordered?: boolean;
    };
    "Sravni.OsagoGateway.Service.Calculations.Models.ComparePolicies.CompanyModel": {
      /** Format: int32 */
      companyId?: number;
      companyName?: string | null;
      price?: string | null;
      paymentUrl?: string | null;
      rows?: components["schemas"]["Sravni.OsagoGateway.Service.Calculations.Models.ComparePolicies.Row"][] | null;
    };
    "Sravni.OsagoGateway.Service.Calculations.Models.ComparePolicies.ComparePoliciesResult": {
      hash?: string | null;
      banner?: components["schemas"]["Sravni.OsagoGateway.Service.Calculations.Models.ComparePolicies.BannerModel"];
    };
    "Sravni.OsagoGateway.Service.Calculations.Models.ComparePolicies.Row": {
      columns?: components["schemas"]["Sravni.OsagoGateway.Service.Calculations.Models.ComparePolicies.Column"][] | null;
      color?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.ColorType"];
      isBold?: boolean;
    };
    "Sravni.OsagoGateway.Service.Calculations.Models.DriverKbm": {
      /** @description Фамилия */
      lastName?: string | null;
      /** @description Отчество */
      middleName?: string | null;
      /** @description Имя */
      firstName?: string | null;
      /** Format: double */
      kbm?: number | null;
    };
    "Sravni.OsagoGateway.Service.Calculations.Models.KbmInfo": {
      drivers?: components["schemas"]["Sravni.OsagoGateway.Service.Calculations.Models.DriverKbm"][] | null;
      multidrive?: components["schemas"]["Sravni.OsagoGateway.Service.Calculations.Models.Multidrive"];
    };
    /** @description Дефолтный КБМ при мультидрайве */
    "Sravni.OsagoGateway.Service.Calculations.Models.Multidrive": {
      /** Format: double */
      defaultKbm?: number;
    };
    /** @description Информация о рекомендуемой ДНД */
    "Sravni.OsagoGateway.Service.Calculations.Models.RecommendedStartDateDto": {
      /** @description Рекомендуемая дата */
      startDate?: string | null;
      /** @description Признак того что рекомендуемая ДНД основана на данных о прошлом полисе */
      isByPolicy?: boolean;
      /** @description Признак того что рекомендуемая ДНД основана на раннем заказе */
      isByEarlyOrder?: boolean;
      /** @description Название предыдущей страховой */
      insCompanyName?: string | null;
      /**
       * Format: date-time
       * @description Дата окончания прошлого полиса
       */
      lastPolicyEndDate?: string | null;
      /**
       * Format: int32
       * @description Id предыдущей страховой
       */
      insCompanyId?: number;
      /**
       * Format: double
       * @description Цена прошлого полиса
       */
      lastPolicyPrice?: number;
    };
    "Sravni.OsagoGateway.Service.Calculations.Models.StartCalculationRequest": {
      /**
       * Format: int32
       * @description id бренда ТС
       */
      brandId?: number;
      /**
       * Format: int32
       * @description год выпуска ТС
       */
      year?: number;
      /**
       * Format: int32
       * @description id модели ТС
       */
      modelId?: number;
      /** @description Модификация ТС */
      modification?: string | null;
      /**
       * Format: int32
       * @description мощность ТС
       */
      enginePower?: number;
      /** @description населенный пункт регистрации собственника */
      registration?: string | null;
      /** @description населенный пункт получения */
      getting?: string | null;
      /**
       * Format: date-time
       * @description Дата начала договора || расчета кбм
       */
      policyStartDate?: string;
      driversInfo?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.DriversInfo"];
      /** @description Номер автомобиля */
      carNumber?: string | null;
      /** @description VIN ТС */
      vin?: string | null;
      /** @description Номер кузова */
      bodyNumber?: string | null;
      /** @description Номер Шасси */
      chassisNumber?: string | null;
      /**
       * Format: int32
       * @description id пользователя в системе сравни.ру
       */
      userId?: number | null;
      owner?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.OsagoPerson"];
      insurer?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.OsagoPerson"];
      carDocument?: components["schemas"]["Sravni.OsagoGateway.Service.Calculations.Models.CarDocumentInfoNullableDate"];
      utm?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.UtmQuery"];
      partner?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.PartnerQuery"];
      promotionQuery?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.PromotionQuery"];
      /** @description Id в системе Amplitude */
      amplitudeId?: string | null;
      /** @description Для кастомной прометки: например (Основной веб-сайт, новый сайт, мобилка и т.д.) */
      platform?: string | null;
      /** @description Пролонгация? */
      isProlongation?: boolean;
      /** @description Признак того, что квери получена из пролонгации. Делаем отдельно от IsProlongation, чтобы не было проблем при создании заказа */
      fromProlongation?: boolean;
      /**
       * Format: int32
       * @description Аккаунт под которым выполняется сохранение в СК
       */
      accountPriority?: number | null;
      previousPolicy?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.PreviousPolicy"];
      /** @description Опциональный ключ пролонгации */
      prolongationKey?: string | null;
      /** @description Метка контекстной рекламы */
      clid?: string | null;
      vehicleCategory?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.VehicleCategory"];
      isResident?: boolean;
      /** Format: int32 */
      usageMonthsPerYear?: number;
      /** @description Промокод */
      benefitCode?: string | null;
    };
    /**
     * @description Возможно есть что поправить надо сообщить фронту где
     * @enum {string}
     */
    "Sravni.OsagoGateway.Service.Core.Polling.AlertAction": "none" | "goToDriverStep" | "disableUpsale" | "policyPriceChange" | "enterRegNumber" | "turnOffDrivers" | "policyEndDateText" | "takePayUrlOnTheNextStep" | "recommendedInsuranceCompany" | "cashbackMobile" | "enterSTS" | "enterRegNumberAndSTS" | "openPromoModal";
    "Sravni.OsagoGateway.Service.Core.Polling.AlertModel": {
      alert?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.ColorType"];
      title?: string | null;
      description?: string | null;
      modalTitle?: string | null;
      url?: string | null;
      action?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.AlertAction"];
      code?: string | null;
    };
    /**
     * @description Цвет
     * @enum {string}
     */
    "Sravni.OsagoGateway.Service.Core.Polling.ColorType": "green" | "red" | "orange" | "blue" | "gray" | "white" | "yellow" | "dark" | "violet";
    /**
     * @description Тип цвета
     * @enum {string}
     */
    "Sravni.OsagoGateway.Service.Core.Polling.ColorVariant": "primary" | "secondary";
    "Sravni.OsagoGateway.Service.Core.Polling.CompanyInfo": {
      main?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.MainInfo"];
      hidden?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.HiddenInfo"];
      /** Format: int32 */
      id?: number;
      name?: string | null;
    };
    "Sravni.OsagoGateway.Service.Core.Polling.ExtPollingResult": {
      /** @description процесс завершен? */
      isCompleted?: boolean;
      /** @description предложения к выводу */
      offers?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.Offer"][] | null;
      orderInfo?: components["schemas"]["Sravni.OsagoGateway.Service.Orders.Models.OrderInfo"];
      /** @description алерты к выводу */
      alerts?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.AlertModel"][] | null;
      kbmInfo?: components["schemas"]["Sravni.OsagoGateway.Service.Calculations.Models.KbmInfo"];
      economyRecommendations?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.EconomyRecommenadtions.EconomyRecommendations"];
      benefitSuccess?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.AlertModel"][] | null;
      /** Format: int32 */
      benefitCodeSecondsLeft?: number | null;
      recommendedStartDate?: components["schemas"]["Sravni.OsagoGateway.Service.Calculations.Models.RecommendedStartDateDto"];
      marketingBanner?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Recommendations.MarketingBannerModel"][] | null;
      unavailableOffers?: components["schemas"]["Sravni.OsagoGateway.Service.Orders.Models.OrderInfo.ShortCompanyInfo"][] | null;
      inProgressOffers?: components["schemas"]["Sravni.OsagoGateway.Service.Orders.Models.OrderInfo.ShortCompanyInfo"][] | null;
    };
    "Sravni.OsagoGateway.Service.Core.Polling.FormulaInfo": {
      resultText?: string | null;
      multipliers?: string[] | null;
    };
    "Sravni.OsagoGateway.Service.Core.Polling.GoodBadInfo": {
      positiveTag?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.InternalRow"];
      negativeTag?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.InternalRow"];
    };
    "Sravni.OsagoGateway.Service.Core.Polling.HiddenInfo": {
      rating?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.RatingRow"];
      price?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.PriceRow"];
      promo?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.PromoRow"];
      alerts?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.AlertModel"][] | null;
      aboutCompany?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.Row"];
      offices?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.Row"];
    };
    "Sravni.OsagoGateway.Service.Core.Polling.InternalRow": {
      title?: string | null;
      description?: string | null;
      label?: string | null;
      value?: string | null;
      color?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.ColorType"];
    };
    "Sravni.OsagoGateway.Service.Core.Polling.MainInfo": {
      /** Format: double */
      stars?: number;
      /** Format: int32 */
      promoCount?: number;
      columns?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.TitleDescription"][] | null;
    };
    "Sravni.OsagoGateway.Service.Core.Polling.Offer": {
      company?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.CompanyInfo"];
      /** Format: int32 */
      osagoId?: number;
      /** Format: double */
      price?: number;
      fractionalPaymentInfo?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.FractionalPaymentInfo"];
      isProlongation?: boolean;
      upsaleResults?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.UpsaleDto"][] | null;
      /** Format: date-time */
      startDate?: string | null;
      tags?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.Tag"][] | null;
      upperTags?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.UpperTag"][] | null;
      /** Format: double */
      tb?: number | null;
      alerts?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.AlertModel"][] | null;
      calcHash?: string | null;
      finallyPrice?: string | null;
      /** @description Признак Спонсора раздела */
      isSectionSponsor?: boolean;
      policyBlankLink?: string | null;
    };
    /** @enum {string} */
    "Sravni.OsagoGateway.Service.Core.Polling.OfferTagType": "promo" | "insuranceCompany" | "startDate" | "upSale" | "recommendedCompany" | "cheapestCompany" | "cashbackCalculation" | "cashbackOrder" | "timeLimitedCashbackCalculation" | "timeLimitedCashbackOrder" | "promoWithDetails";
    "Sravni.OsagoGateway.Service.Core.Polling.PollingResult": {
      /** @description процесс завершен? */
      isCompleted?: boolean;
      /** @description предложения к выводу */
      offers?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.Offer"][] | null;
      orderInfo?: components["schemas"]["Sravni.OsagoGateway.Service.Orders.Models.OrderInfo"];
      /** @description алерты к выводу */
      alerts?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.AlertModel"][] | null;
      kbmInfo?: components["schemas"]["Sravni.OsagoGateway.Service.Calculations.Models.KbmInfo"];
      economyRecommendations?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.EconomyRecommenadtions.EconomyRecommendations"];
      benefitSuccess?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.AlertModel"][] | null;
      /** Format: int32 */
      benefitCodeSecondsLeft?: number | null;
      recommendedStartDate?: components["schemas"]["Sravni.OsagoGateway.Service.Calculations.Models.RecommendedStartDateDto"];
      marketingBanner?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Recommendations.MarketingBannerModel"][] | null;
      unavailableOffers?: components["schemas"]["Sravni.OsagoGateway.Service.Orders.Models.OrderInfo.ShortCompanyInfo"][] | null;
      inProgressOffers?: components["schemas"]["Sravni.OsagoGateway.Service.Orders.Models.OrderInfo.ShortCompanyInfo"][] | null;
    };
    "Sravni.OsagoGateway.Service.Core.Polling.PriceRow": {
      title?: string | null;
      subTitle?: string | null;
      comment?: string | null;
      description?: string | null;
      texts?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.TitleDescription"][] | null;
      isOpen?: boolean;
      formula?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.FormulaInfo"];
      formulaRows?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.InternalRow"][] | null;
      price?: string | null;
      priceTitle?: string | null;
    };
    "Sravni.OsagoGateway.Service.Core.Polling.PromoRow": {
      title?: string | null;
      subTitle?: string | null;
      comment?: string | null;
      description?: string | null;
      texts?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.TitleDescription"][] | null;
      isOpen?: boolean;
      promos?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.OsagoPromo.Models.PromoProgramDto"][] | null;
    };
    "Sravni.OsagoGateway.Service.Core.Polling.RatingDetalization": {
      /** Format: int32 */
      star1Count?: number;
      /** Format: int32 */
      star2Count?: number;
      /** Format: int32 */
      star3Count?: number;
      /** Format: int32 */
      star4Count?: number;
      /** Format: int32 */
      star5Count?: number;
    };
    "Sravni.OsagoGateway.Service.Core.Polling.RatingRow": {
      title?: string | null;
      subTitle?: string | null;
      comment?: string | null;
      description?: string | null;
      texts?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.TitleDescription"][] | null;
      isOpen?: boolean;
      detalization?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.RatingDetalization"];
      goodBad?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.GoodBadInfo"];
      ratings?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.InternalRow"][] | null;
    };
    "Sravni.OsagoGateway.Service.Core.Polling.Row": {
      title?: string | null;
      subTitle?: string | null;
      comment?: string | null;
      description?: string | null;
      texts?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.TitleDescription"][] | null;
      isOpen?: boolean;
    };
    /** @description Additional affer infos */
    "Sravni.OsagoGateway.Service.Core.Polling.Tag": {
      type?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.OfferTagType"];
      /** @description Additional offer info text */
      title?: string | null;
      color?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.ColorType"];
      colorVariant?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.ColorVariant"];
    };
    "Sravni.OsagoGateway.Service.Core.Polling.TitleDescription": {
      title?: string | null;
      description?: string | null;
    };
    /** @description UpperTag */
    "Sravni.OsagoGateway.Service.Core.Polling.UpperTag": {
      type?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.OfferTagType"];
      /** @description Additional offer info text */
      title?: string | null;
      color?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.ColorType"];
      colorVariant?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.ColorVariant"];
      /** @description Text */
      text?: string | null;
      /** @description Идентификатор */
      code?: string | null;
    };
    "Sravni.OsagoGateway.Service.Core.Polling.UpsaleDto": {
      /** Format: double */
      price?: number;
      name?: string | null;
      description?: string | null;
      finallyPrice?: string | null;
    };
    "Sravni.OsagoGateway.Service.Core.UserRequest": {
      userToken?: string | null;
    };
    /**
     * @description Тип документа на ТС
     * @enum {string}
     */
    "Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.CarDocumentType": "pts" | "sts" | "ePts";
    /**
     * @description ограничение по водителям
     * @enum {string}
     */
    "Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.DriverAmount": "limited" | "unlimited";
    /** @description Информация о водителе */
    "Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.DriverInfo": {
      /** @description Фамилия */
      lastName?: string | null;
      /** @description Отчество */
      middleName?: string | null;
      /** @description Имя */
      firstName?: string | null;
      /**
       * Format: int64
       * @description Идентификатор
       */
      id?: number;
      /**
       * Format: date-time
       * @description Дата рождения
       */
      birthDate?: string;
      license?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.DriverLicense"];
      previousInfo?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.PreviousDriverInfo"];
      /**
       * Format: int32
       * @description Возраст
       */
      age?: number;
      /**
       * Format: int32
       * @description Стаж
       */
      experience?: number;
      /** @description полное имя */
      fullName?: string | null;
    };
    /** @description данные В/У */
    "Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.DriverLicense": {
      /** @description серия паспорта */
      series?: string | null;
      /** @description номер паспорта */
      number?: string | null;
      /**
       * Format: date-time
       * @description дата выдачи первых В/У. написанно в В/У или в последнем договоре ОСАГО
       */
      date?: string;
    };
    /** @description Информация о водителях */
    "Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.DriversInfo": {
      driverAmount?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.DriverAmount"];
      /** @description список водителей */
      drivers?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.DriverInfo"][] | null;
    };
    /** @description Рекомендация по исключению водителя с худшим коэффициентом возраста/стажа */
    "Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.EconomyRecommenadtions.AgeExperienceRecommendation": {
      worstDriverFirstName?: string | null;
      worstDriverLastName?: string | null;
      worstDriverMiddleName?: string | null;
      /** Format: date-time */
      worstDriverBirthDate?: string;
      /** Format: double */
      worstDriverAgeExperienceCoeff?: number;
      /** Format: double */
      economyMin?: number;
      /** Format: double */
      economyMax?: number;
      text?: string | null;
    };
    /** @description Рекомендация о количестве водителей */
    "Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.EconomyRecommenadtions.DriversCountRecommendation": {
      /** Format: int32 */
      curentDriversCount?: number;
      /** Format: int32 */
      suitableDriversCount?: number;
      text?: string | null;
    };
    /** @description Рекомендации по экономии на покупке полиса */
    "Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.EconomyRecommenadtions.EconomyRecommendations": {
      kbmRecommendation?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.EconomyRecommenadtions.KbmRecommendation"];
      ownerRecommendation?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.EconomyRecommenadtions.OwnerRecommendation"];
      startDateRecommendation?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.EconomyRecommenadtions.StartDateRecommendation"];
      driversCountRecommendation?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.EconomyRecommenadtions.DriversCountRecommendation"];
      ageExperienceRecommendation?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.EconomyRecommenadtions.AgeExperienceRecommendation"];
    };
    /** @description Рекомендация по исключению водителя с худшим КБМ */
    "Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.EconomyRecommenadtions.KbmRecommendation": {
      worstDriverFirstName?: string | null;
      worstDriverLastName?: string | null;
      worstDriverMiddleName?: string | null;
      /** Format: date-time */
      worstDriverBirthDate?: string;
      /** Format: double */
      worstDriverKbm?: number;
      /** Format: double */
      economyMin?: number;
      /** Format: double */
      economyMax?: number;
      text?: string | null;
    };
    /** @description Рекомендация о том, что владелец и страхователь должен быть одним лицом */
    "Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.EconomyRecommenadtions.OwnerRecommendation": {
      ownerName?: string | null;
      insurerName?: string | null;
      text?: string | null;
    };
    /** @description Рекомендация о ДНД полиса */
    "Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.EconomyRecommenadtions.StartDateRecommendation": {
      /** Format: date-time */
      currentStartDate?: string;
      /** Format: date-time */
      recommendedStartDate?: string;
      /** Format: date-time */
      suitableStartDateMin?: string;
      /** Format: date-time */
      suitableStartDateMax?: string;
      text?: string | null;
    };
    /** @description Информация об оплате долями. */
    "Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.FractionalPaymentInfo": {
      /**
       * Format: double
       * @description Стоимость с учетом комиссии.
       */
      price?: number;
      /**
       * Format: double
       * @description Комиссия.
       */
      commission?: number;
      /** @description Ссылка оплаты. */
      paymentUrl?: string | null;
      /** @description Информация о частичных платежах. */
      paymentParts?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.FractionalPaymentPart"][] | null;
    };
    /** @description Информация о частичном платеже. */
    "Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.FractionalPaymentPart": {
      /**
       * Format: double
       * @description Сумма частичного платежа.
       */
      paymentSum?: number;
      /**
       * Format: date-time
       * @description Дата частичного платежа.
       */
      paymentDate?: string;
    };
    "Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.OsagoPerson": {
      /** @description Фамилия */
      lastName?: string | null;
      /** @description Отчество */
      middleName?: string | null;
      /** @description Имя */
      firstName?: string | null;
      /** @description полное имя */
      fullName?: string | null;
      passport?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.Passport"];
      /**
       * Format: date-time
       * @description Дата рождения
       */
      birthDate?: string;
      gender?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.Sex"];
      /** @description Телефон (моб.) */
      phone?: string | null;
      /** @description e-mail */
      email?: string | null;
      /** @description прокси e-mail */
      proxyEmail?: string | null;
      /** @description Адрес регистрации */
      registrationAddress?: string | null;
      /**
       * Format: int32
       * @description Id Регионального центра
       */
      regionalCenterId?: number | null;
      /**
       * Format: int32
       * @description Возраст
       */
      age?: number;
    };
    /** @description Партнерский блок */
    "Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.PartnerQuery": {
      /** @description канал */
      medium?: string | null;
      /** @description источник */
      source?: string | null;
      /** @description компания */
      campaign?: string | null;
      /** @description Контент. */
      content?: string | null;
      /** @description Поисковый запрос. */
      term?: string | null;
      /** @description google id */
      uaClientId?: string | null;
      /** @description yandex id */
      ymClientId?: string | null;
      /**
       * Format: int32
       * @description Id агента пригласившего в реферальную программу пользователя продавшего заказ
       */
      referId?: number | null;
      /** @description Площадка продажи полиса */
      platform?: string | null;
      /** @description доп метка */
      subId?: string | null;
      /** @description Id агента в системе Альфа страхования */
      alfaUserId?: string | null;
      /** @description Id агента в системе Ренесанс страхования */
      renessansUserId?: string | null;
      /** @description доп метка роута для субагентов АК */
      subagentRoute?: string | null;
      /**
       * Format: int32
       * @description партнерские данные (Id аффилиата по hasoffers)
       */
      affId?: number | null;
      /**
       * Format: int32
       * @description партнерские данные( Id оффера из hasoffers )
       */
      offerId?: number | null;
      /** @description партнерские данные (Id/externalId виджета по админке партнерки) */
      affSub1?: string | null;
      /** @description партнерские данные (Id/externalId виджета по админке партнерки) */
      affSub2?: string | null;
      /** @description партнерские данные (Id/externalId виджета по админке партнерки) */
      affSub3?: string | null;
      /** @description партнерские данные (Id/externalId виджета по админке партнерки) */
      affSub4?: string | null;
      /** @description партнерские данные (Id/externalId виджета по админке партнерки) */
      affSub5?: string | null;
      /** @description партнерские данные (Id площадки) */
      sourceId?: string | null;
      /** @description партнерские данные (Id клика перехода на сравни.ру с паретнерской площадки) */
      transactionId?: string | null;
      /** @description Регион агента (по КЛАДР) */
      agentRegion?: string | null;
      /**
       * Format: date-time
       * @description Дата установки куки
       */
      setDate?: string | null;
    };
    /** @description данные паспорта */
    "Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.Passport": {
      /** @description серия паспорта */
      series?: string | null;
      /** @description номер паспорта */
      number?: string | null;
      /**
       * Format: date-time
       * @description Дата выдачи паспорта
       */
      issueDate?: string | null;
    };
    "Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.PreviousDriverInfo": {
      /** @description Фамилия */
      lastName?: string | null;
      /** @description Отчество */
      middleName?: string | null;
      /** @description Имя */
      firstName?: string | null;
      /** @description полное имя */
      fullName?: string | null;
      license?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.DriverLicense"];
    };
    /** @description данные прошлого полиса */
    "Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.PreviousPolicy": {
      /** @description Серия предыдущего полиса ОСАГО */
      series?: string | null;
      /** @description Номер предыдущего полиса ОСАГО */
      number?: string | null;
      /** @description компания, выдавшая полис */
      company?: string | null;
      /**
       * Format: int32
       * @description id Ск
       */
      companyId?: number;
      /**
       * Format: date-time
       * @description Дата окончания полиса
       */
      policyEndDate?: string | null;
      /** @description Vin по полису */
      vin?: string | null;
      /** @description Номер ТС по полису */
      carNumber?: string | null;
      /** @description Номер Кузова по полису */
      bodyNumber?: string | null;
      /** @description город собственика по полису */
      location?: string | null;
      /**
       * Format: double
       * @description Цена полиса
       */
      price?: number | null;
      /**
       * Format: date-time
       * @description Д/Р страхователя
       */
      insurantBirthDate?: string | null;
      /** @description ФИО страхователя */
      insurantName?: string | null;
      /**
       * Format: double
       * @description Кбм
       */
      kbm?: number | null;
      /**
       * Format: date-time
       * @description Д/Р собственика
       */
      ownerBirthDate?: string | null;
      /** @description ФИО собственика */
      ownerName?: string | null;
      /** @description Полис приобретен через платформу "Сравни.ру" */
      isPurchasedViaSravni?: boolean;
    };
    /** @description Promotion метки */
    "Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.PromotionQuery": {
      /** @description источник */
      source?: string | null;
      /** @description компания */
      campaign?: string | null;
      category?: string | null;
      sub1?: string | null;
      sub2?: string | null;
    };
    /**
     * @description пол
     * @enum {string}
     */
    "Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.Sex": "unknown" | "male" | "female";
    /** @description Utm метки */
    "Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.UtmQuery": {
      /** @description канал */
      medium?: string | null;
      /** @description источник */
      source?: string | null;
      /** @description компания */
      campaign?: string | null;
      /** @description Контент. */
      content?: string | null;
      /** @description Поисковый запрос. */
      term?: string | null;
      /** @description google id */
      uaClientId?: string | null;
      /** @description yandex id */
      ymClientId?: string | null;
      /**
       * Format: date-time
       * @description Дата установки куки
       */
      setDate?: string | null;
    };
    /**
     * @description Категория ВУ
     * @enum {string}
     */
    "Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.VehicleCategory": "b" | "c" | "a" | "d" | "e";
    "Sravni.OsagoGateway.Service.ExternalDependencies.OsagoPromo.Models.BonusInfo": {
      bonusValue?: string | null;
      bonusUnit?: string | null;
      bonusDescription?: string | null;
      servicePlace?: string | null;
    };
    "Sravni.OsagoGateway.Service.ExternalDependencies.OsagoPromo.Models.ExternalPromoData": {
      title?: string | null;
      description?: string[] | null;
    };
    "Sravni.OsagoGateway.Service.ExternalDependencies.OsagoPromo.Models.PartnerAbout": {
      name?: string | null;
      description?: string | null;
      logoMinUrl?: string | null;
      /** @description Рекламное название */
      advertisingName?: string | null;
      /** @description Рекламный токен */
      advertisingToken?: string | null;
    };
    /** @description Промакция */
    "Sravni.OsagoGateway.Service.ExternalDependencies.OsagoPromo.Models.PromoProgramDto": {
      /**
       * Format: int32
       * @description CampaignId
       */
      campaignId?: number;
      /** @description Код */
      code?: string | null;
      /** @description Заголовок */
      title?: string | null;
      /** @description Короткая информация о промо */
      shortPromoInfo?: string | null;
      /** @description Описание */
      description?: string | null;
      /** @description Пояснение */
      subDescription?: string | null;
      /** @description Ссылка на лого акции */
      logoUrl?: string | null;
      /** @description Ссылка на лого для короткой карточки */
      logoBigUrl?: string | null;
      /** @description Ссылка на правила акции */
      ruleUrl?: string | null;
      /** @description Ссылка на внешние акции */
      externalRuleUrl?: string | null;
      bonusInfo?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.OsagoPromo.Models.BonusInfo"];
      about?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.OsagoPromo.Models.PartnerAbout"];
      /** @description Признак того что акция общая и действует на все предложения */
      isGeneral?: boolean;
      /**
       * Format: date-time
       * @description Дата окончания предложения
       */
      expirationDate?: string | null;
      /** @description Дата окончания предложения */
      data?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.OsagoPromo.Models.ExternalPromoData"][] | null;
    };
    /** @description Адрес */
    "Sravni.OsagoGateway.Service.ExternalDependencies.ProfileLoader.Models.AdditionalAddressInfo": {
      /** @description Квартира */
      flatNumber?: string | null;
      /** @description Регион */
      region?: string | null;
    };
    /** @description Права */
    "Sravni.OsagoGateway.Service.ExternalDependencies.ProfileLoader.Models.DriverLicense": {
      /** @description Серия и номер ВУ */
      number?: string | null;
      /**
       * Format: date-time
       * @description Дата начала стажа
       */
      experienceStartDate?: string | null;
      /**
       * Format: int32
       * @description Год начала стажа
       */
      experienceStartYear?: number | null;
    };
    /** @description Данные паспорта */
    "Sravni.OsagoGateway.Service.ExternalDependencies.ProfileLoader.Models.Passport": {
      /** @description Серия и номер паспорта */
      number?: string | null;
      /**
       * Format: date-time
       * @description Дата выдачи паспорта
       */
      obtainingDate?: string | null;
    };
    "Sravni.OsagoGateway.Service.ExternalDependencies.ProfileLoader.Models.PersonAddress": {
      data?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.ProfileLoader.Models.AdditionalAddressInfo"];
      /** @description Форматированный адрес для отображения */
      formattedAddress?: string | null;
      /** @description ФИАС-уровень на основе форматированного адреса */
      formattedFiasLevel?: string | null;
    };
    /** @description Старые данные о ФИО и ВУ */
    "Sravni.OsagoGateway.Service.ExternalDependencies.ProfileLoader.Models.PreviousDriverInfo": {
      /** @description Фамилия */
      lastName?: string | null;
      /** @description Отчество */
      middleName?: string | null;
      /** @description Имя */
      firstName?: string | null;
      license?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.ProfileLoader.Models.DriverLicense"];
    };
    /** @description Люди из профиля клиента */
    "Sravni.OsagoGateway.Service.ExternalDependencies.ProfileLoader.Models.ProfilePeopleForm": {
      /** @description Люди из профиля клиента */
      people?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.ProfileLoader.Models.ProfilePerson"][] | null;
      /** @description Есть люди с госуслуг */
      withEsia?: boolean;
    };
    /** @description Данные прользователя из профиль сервиса */
    "Sravni.OsagoGateway.Service.ExternalDependencies.ProfileLoader.Models.ProfilePerson": {
      /** @description Данные получены из Госуслуг */
      fromEsia?: boolean;
      /** @description Роли пользователя Sravni.OsagoGateway.Service.ExternalDependencies.ProfileLoader.Models.ProfileRole */
      roles?: string[] | null;
      /** @description Фамилия */
      lastName?: string | null;
      /** @description Отчество */
      middleName?: string | null;
      /** @description Имя */
      firstName?: string | null;
      /** @description Однофамилец владельца профиля */
      namesake?: boolean;
      /** @description полное имя */
      fullName?: string | null;
      passport?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.ProfileLoader.Models.Passport"];
      /**
       * Format: date-time
       * @description Дата рождения
       */
      birthDate?: string;
      /** @description Телефон (моб.) */
      phone?: string | null;
      /** @description e-mail */
      email?: string | null;
      license?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.ProfileLoader.Models.DriverLicense"];
      previousInfo?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.ProfileLoader.Models.PreviousDriverInfo"];
      address?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.ProfileLoader.Models.PersonAddress"];
    };
    "Sravni.OsagoGateway.Service.ExternalDependencies.Recommendations.MarketingBannerModel": {
      imageUrl?: string | null;
      description?: string[] | null;
      /** Format: int32 */
      durationInSeconds?: number;
    };
    "Sravni.OsagoGateway.Service.ExternalDependencies.Recommendations.PollingWithRecomendationResult": {
      /** @description процесс завершен? */
      isCompleted?: boolean;
      /** @description предложения к выводу */
      offers?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.Offer"][] | null;
      orderInfo?: components["schemas"]["Sravni.OsagoGateway.Service.Orders.Models.OrderInfo"];
      /** @description алерты к выводу */
      alerts?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.AlertModel"][] | null;
      kbmInfo?: components["schemas"]["Sravni.OsagoGateway.Service.Calculations.Models.KbmInfo"];
      economyRecommendations?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.EconomyRecommenadtions.EconomyRecommendations"];
      benefitSuccess?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.AlertModel"][] | null;
      /** Format: int32 */
      benefitCodeSecondsLeft?: number | null;
      unavailableOffers?: components["schemas"]["Sravni.OsagoGateway.Service.Orders.Models.OrderInfo.ShortCompanyInfo"][] | null;
      inProgressOffers?: components["schemas"]["Sravni.OsagoGateway.Service.Orders.Models.OrderInfo.ShortCompanyInfo"][] | null;
      sravniRecommendations?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Recommendations.SravniRecommendations"];
      /** @description Скрытые предложения к выводу */
      hiddenOffers?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.Offer"][] | null;
      previousPolicyInfo?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Recommendations.PreviousPolicyInfo"];
      previousCompanyRefuse?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Recommendations.PreviousCompanyRefuse"];
      /** @description алерты к выводу пролонгации */
      prolongationAlerts?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.AlertModel"][] | null;
      marketingBanner?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Recommendations.MarketingBannerModel"][] | null;
      recommendedStartDate?: components["schemas"]["Sravni.OsagoGateway.Service.Calculations.Models.RecommendedStartDateDto"];
    };
    "Sravni.OsagoGateway.Service.ExternalDependencies.Recommendations.PreviousCompanyRefuse": {
      color?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.ColorType"];
      colorVariant?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.ColorVariant"];
      /** @description Описание */
      description?: string | null;
      /**
       * Format: int32
       * @description Id компании
       */
      companyId?: number;
    };
    "Sravni.OsagoGateway.Service.ExternalDependencies.Recommendations.PreviousPolicyInfo": {
      color?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.ColorType"];
      colorVariant?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.ColorVariant"];
      /** @description Заголовок */
      title?: string | null;
      /** @description Id компании */
      info?: string[] | null;
    };
    "Sravni.OsagoGateway.Service.ExternalDependencies.Recommendations.Recommendations": {
      label?: string | null;
      description?: string | null;
      linkText?: string | null;
      action?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.AlertAction"];
    };
    "Sravni.OsagoGateway.Service.ExternalDependencies.Recommendations.SravniRecommendations": {
      title?: string | null;
      recommendationsList?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Recommendations.Recommendations"][] | null;
    };
    "Sravni.OsagoGateway.Service.Orders.Models.OrderInfo": {
      paymentUrl?: string | null;
      orderStatus?: components["schemas"]["Sravni.OsagoGateway.Service.Orders.Models.OrderStatus"];
      policyStartDate?: string | null;
      newPolicyStartDate?: string | null;
      /** Format: int32 */
      osagoId?: number;
      calcHash?: string | null;
      orderHash?: string | null;
      isProlongation?: boolean;
      finallyPrice?: string | null;
      orderDate?: string | null;
      company?: components["schemas"]["Sravni.OsagoGateway.Service.Orders.Models.OrderInfo.ShortCompanyInfo"];
      alert?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.AlertModel"];
      alerts?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.AlertModel"][] | null;
      tags?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.Tag"][] | null;
      upperTags?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.UpperTag"][] | null;
      startDateText?: string | null;
      /** Format: double */
      searchPrice?: number;
      isPriceChangedBad?: boolean;
      isPriceChanged?: boolean;
      /** Format: double */
      price?: number;
      fractionalPaymentInfo?: components["schemas"]["Sravni.OsagoGateway.Service.ExternalDependencies.Osago.Models.FractionalPaymentInfo"];
      startDate?: string | null;
      upsaleResults?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.UpsaleDto"][] | null;
      draftFullUrl?: string | null;
      offer?: components["schemas"]["Sravni.OsagoGateway.Service.Core.Polling.Offer"];
    };
    "Sravni.OsagoGateway.Service.Orders.Models.OrderInfo.ShortCompanyInfo": {
      /** Format: int32 */
      id?: number;
      name?: string | null;
    };
    /**
     * @description результат общей операции сохранения и проверки
     * @enum {string}
     */
    "Sravni.OsagoGateway.Service.Orders.Models.OrderStatus": "failed" | "loading" | "dateChanged" | "success";
    /** @enum {string} */
    "Sravni.OsagoPromo.Shared.Enums.BenefitType": "percent" | "amount";
    /** @enum {string} */
    "Sravni.OsagoPromo.Shared.Enums.ProductType": "osago";
    /** @enum {string} */
    "Sravni.OsagoPromo.Shared.Enums.PromoCodeStatus": "valid" | "notFound" | "activated" | "outDated";
    /** @enum {string} */
    "Sravni.OsagoPromo.Shared.Enums.PromoPartner": "mir" | "pcO10Moscow" | "pcO7MR" | "miR2" | "dodo" | "timeLimitedCashback" | "casH10" | "flashSale1" | "halvaCardPromo" | "vskSoglasieDobor" | "newYearGift" | "newYearGiftPolicy" | "promokodus";
    "Sravni.OsagoPromo.Shared.Models.LinkPromoCodeRequest": {
      code?: string | null;
      externalId?: string | null;
      /** Format: date-time */
      orderDate?: string;
      productType?: components["schemas"]["Sravni.OsagoPromo.Shared.Enums.ProductType"];
    };
    "Sravni.OsagoPromo.Shared.Models.PromoCodeInfo": {
      code?: string | null;
      /** Format: int32 */
      activationCount?: number;
      productType?: components["schemas"]["Sravni.OsagoPromo.Shared.Enums.ProductType"];
      /** Format: date-time */
      dateCreate?: string;
      isActive?: boolean;
      name?: string | null;
      description?: string | null;
      promoPartner?: components["schemas"]["Sravni.OsagoPromo.Shared.Enums.PromoPartner"];
      /** Format: double */
      benefitValue?: number;
      benefitType?: components["schemas"]["Sravni.OsagoPromo.Shared.Enums.BenefitType"];
      /** Format: date-time */
      dateFrom?: string;
      /** Format: date-time */
      expirationDate?: string;
      /** Format: int32 */
      programId?: number;
      programIsExtended?: boolean;
      geos?: components["schemas"]["Sravni.OsagoPromo.Shared.Models.PromoGeo"][] | null;
      organisations?: components["schemas"]["Sravni.OsagoPromo.Shared.Models.PromoOrganisation"][] | null;
    };
    "Sravni.OsagoPromo.Shared.Models.PromoCodeValidationResult": {
      promoCode?: string | null;
      isActive?: boolean;
      error?: string | null;
      status?: components["schemas"]["Sravni.OsagoPromo.Shared.Enums.PromoCodeStatus"];
    };
    "Sravni.OsagoPromo.Shared.Models.PromoGeo": {
      route?: string | null;
    };
    "Sravni.OsagoPromo.Shared.Models.PromoOrganisation": {
      organisation?: string | null;
      /** Format: double */
      benefitValue?: number;
      isApplicableToZeroIncome?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
