export const config = {
  GATEWAY: process.env.GATEWAY || '',
  DADATA: process.env.DADATA,
  COOKIES: process.env.COOKIES,
  CLIENT_ID_BFF: process.env.CLIENT_ID_BFF || '',
  CLIENT_ID: process.env.CLIENT_ID || '',
  CLIENT_SECRET_BFF: process.env.CLIENT_SECRET_BFF || '',
  CLIENT_SECRET: process.env.CLIENT_SECRET || '',
  AUTO_SERVICE_CAR_INFO_SCOPE: process.env.AUTO_SERVICE_CAR_INFO_SCOPE || '',
  AUTO_SERVICE_PARSER_INFO_SCOPE: process.env.AUTO_SERVICE_PARSER_INFO_SCOPE || '',
  OSAGO_SERVICE_DC_INFO_SCOPE: process.env.OSAGO_SERVICE_DC_INFO_SCOPE || '',
  OSAGOGATEWAY_SERVICE_SCOPE: process.env.OSAGOGATEWAY_SERVICE_SCOPE || '',
  AUTO: process.env.AUTO || '',
  ISSUER: process.env.ISSUER || '',
  WEB_PATH: process.env.WEB_PATH || '',
  OSAGO_STAFF: process.env.OSAGO_STAFF || '',
  APIGATEWAY: process.env.APIGATEWAY || '',
  IMAGE_VERSION: process.env.IMAGE_VERSION || '',
  API_PATH: process.env.API_PATH || '',
  NODE_ENV: process.env.NODE_ENV || '',
  PORT: process.env.PORT || '',
  LOCATIONS: process.env.LOCATIONS || '',
  INSURANCECOMPANIES: process.env.INSURANCECOMPANIES || '',
  OSAGOGATEWAY: process.env.OSAGOGATEWAY,
  PROMO: process.env.PROMO,
  METADATA: process.env.METADATA || '',
};
